### ISSUE TITLE
Run AF3 with precomputed MSAs but search for templates

### ISSUE THREAD

**Issue by ErezTzvi** [google-deepmind/alphafold3#108]
Hi,

First, many thanks for releasing the AF3 code - it's very exciting to have access to it!

From my understanding, the current setup allows for three configurations:

1. Running the model with both precomputed MSAs and templates,
2. Running with precomputed MSAs and indicating that there are no templates, so the prediction runs without template information,
3. Running with neither MSAs nor templates, allowing the program to compute both.

However, I haven't come across a way to run the prediction using precomputed MSAs while still allowing the model to search for templates. It would make sense to have an option to use precomputed MSAs while still searching for templates.

Is there currently a way to do this, or is this something that could be supported?

Thanks again for all your work on this!

**Comment by Augustin-Zidek** [comment]
Hi, thanks for reporting this. I wasn't sure whether people would need this, but turns out they do. :)

I've added support for this in https://github.com/google-deepmind/alphafold3/commit/cdbcf41b71235ec33338edef1f80e03fb0c6bae4, you will have to update AlphaFold 3 to the latest commit to get this feature (you will also likely have to untar your mmCIF files, see https://github.com/google-deepmind/alphafold3/issues/88).

**Comment by ErezTzvi** [comment]
Thank you so much for the quick response and for supporting this feature! (:
