### ISSUE TITLE
Are SMILES required in the User-provided CCD Format ?

### ISSUE THREAD

**Issue by jkosinski** [google-deepmind/alphafold3#128]
Are SMILES required in User-provided CCD Format ?

https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#user-provided-ccd-format

The example does contain smiles
```
#
_pdbx_chem_comp_descriptor.type SMILES_CANONICAL
_pdbx_chem_comp_descriptor.descriptor 'Oc1ccc(O)c2C(=O)C=CC(=O)c12'
# 
```
but is this information read and required? Could it an arbitrary string in case smiles string is not readily available?

**Comment by jkosinski** [comment]
So far, I tried with various random strings like _pdbx_chem_comp_descriptor.descriptor 'DUPA" and see no difference, closing with a tentative answer that, no, they are not required.

**Comment by Augustin-Zidek** [comment]
Hi, you are right, it is not needed, the example contains even fields that are not necessary. I am planning to document this better (e.g. include a list of mandatory keys in the docs) and also add a validator that checks you have all of the CCD CIF fields that are required and fails if not. I haven't got to it yet due to higher priority issues - please bear with me.

**Comment by Augustin-Zidek** [comment]
Update: The problem is that `_pdbx_chem_comp_descriptor.type` and `_pdbx_chem_comp_descriptor.descriptor` are currently required, but actually not used -- which is a bug. For now the workaround is to set them to e.g. the unset value `?`. However, I am going to push a fix for this tomorrow, as well as improving the documentation and mandatory field checks around this. 

I will post update in https://github.com/google-deepmind/alphafold3/issues/178 once done.

**Comment by Augustin-Zidek** [comment]
Fix submitted in https://github.com/google-deepmind/alphafold3/commit/63132c4e46479512041ef69583a4b07854c21468:

* You will get a nice error is missing any mandatory fields.
* `_pdbx_chem_comp_descriptor` fields no longer mandatory.
* Better documentation.
