### ISSUE TITLE
Anyway to skip predicting if the output directory already have the same name predicted file? 

### ISSUE THREAD

**Issue by sky1ove** [google-deepmind/alphafold3#154]
I'm using interruptible GPUs on Cloud; it could be stopped at some point and I'd like to resume. 

Is there anyway to skip predicting if the output directory already have the same name predicted file?

**Comment by Augustin-Zidek** [comment]
This has been fixed in https://github.com/google-deepmind/alphafold3/commit/26b03e085e56eb0820e316480ad748e9724158a7 -- please update your AlphaFold installation past that commit.

However, this won't skip the existing directory, it will just not overwrite it.

You could modify the code to skip it instead of writing in a new directory.
