### ISSUE TITLE
Typo in Input format guide

### ISSUE THREAD

**Issue by rachelse** [google-deepmind/alphafold3#190]
Hi, I was reading thoroughly the description regarding input format [input.md](https://github.com/google-deepmind/alphafold3/tree/main/docs/input.md). In the MSA Pairing section, I found one counter-intuitive sentence upon my understanding.

[msa-pairing](https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#msa-pairing)
I guess the sentence 
"AlphaFold 3 internally achieves this by looking for the UniProt organism ID in the `pairedMsa` and pairing sequences based on this information." 
should be corrected to 
"AlphaFold 3 internally achieves this by looking for the UniProt organism ID in the `unpairedMsa` and pairing sequences based on this information.", 
since AF3 reconstruct pairedMSA based on the organism ID in unpairedMSA.

Could you confirm if it was typo or my understanding was wrong?
Also, if we want to make pairedMSA properly upon the given unpairedMSA, should the unpairedMSAs provide organism IDs in the header lines?

Thank you providing this kind guide to use AF3 easier!:)

**Comment by joshabramson** [comment]
This is not a typo - the pairedMsa, which contains species information, is used to generate an additional 'paired' msa that is used as well as the unpaired msa. Unlike unpairedMSA, there are some processing steps to create this paired msa.

However, to get a custom paired msa rather than relying on auto-generated paired msa, we recommend that users do the pairing themselves to generate custom unpaired msas with matched rows, and then only use those.
