### ISSUE TITLE
How does AF3 process user-provided CCDs?

### ISSUE THREAD

**Issue by YoavShamir5** [google-deepmind/alphafold3#212]
Hello, my questions have to do with the way AF3 uses the info from a user-provided CCD:
**1)** My understanding is that the ideal coordinates are only used if Rdkit ligand generation fails. But, since the SMILES field is not mandatory at all, what actually happens during this process? I assume that the atom types, connectivity data and bond types are used to generate a SMILES, which you then try to generate an RDkit conformer from. Is this the case? If the user provides a SMILES via _chem_comp.pdbx_smiles, does AF3 even try to use it initially for ligand generation? Or is this field ignored altogether? 
**2)** How are the ideal coordinates used? What do they dictate in the final ligand? Are bonds lengths/angles used strictly, or just as a starting point for the prediction?
**3)** How were covalent ligands prepared during training? For example, acrylamides have a double bond, that becomes a single bond upon covalent binding to a Cys site. Did you use a double or single bond in your input CCDs for training?
**4)** Should all hydrogens be included in the user-provided CCD? or Just polar hydrogens?
**5)** Chirality - from the paper: "The first is that the model outputs do not always respect chirality (Fig. 5b), despite the model receiving reference structures with correct chirality as input features." - are there guidelines on how to increase likelihood of chirality being respected? Where does the issue arise from - is it in the generation of the CCD from some SMILES, generating ideal coordinates with flipped chirality, or can the model scramble chirality even when the ideal coordinates respect it?

**Comment by joshabramson** [comment]
1. The logic for feature extraction for ligands is all handled here: https://github.com/google-deepmind/alphafold3/blob/7fdf96161d61a6e18048e5c62bf7e1d711992943/src/alphafold3/model/features.py#L1474 - if the ligand name is in ccd (including custom user codes from the input), we use ccd entirely, without ever going via SMILES. Otherwise, we use SMILES and generate all information via rdkit.

2. The ideal co-ordinates are used if the conformer generation fails. If the release date is before the training cutoff date and ideal coordinates are not available, we fall back further to the reference coordinates. Code is here: https://github.com/google-deepmind/alphafold3/blob/7fdf96161d61a6e18048e5c62bf7e1d711992943/src/alphafold3/model/features.py#L1435 . Once we have conformer coordinates we use the raw coordinates and distances as input to the model: https://github.com/google-deepmind/alphafold3/blob/7fdf96161d61a6e18048e5c62bf7e1d711992943/src/alphafold3/model/diffusion/atom_cross_attention.py#L44 and https://github.com/google-deepmind/alphafold3/blob/7fdf96161d61a6e18048e5c62bf7e1d711992943/src/alphafold3/model/diffusion/atom_cross_attention.py#L76-L91 

3. The model has no notion of single of double bonds, although it might be able to deduce that for intra-ligand bonds by considering the conformer coordinates.

4. No hydrogens should be included for Alphafold 3.

5. As done for Posebusters in the paper, running multiple seeds considering chiral correctness when ranking can help alleviate the problem. It is unclear where the issue comes from, there are multiple possibilities.

**Comment by YoavShamir5** [comment]
Thanks a lot for your quick and helpful input, @joshabramson.
- Regrading 1) - According to this, I think the input user-provided CCD guidelines may use a clarification at:
"The main pieces of information used are the atom names and elements, bonds, and also the ideal coordinates (pdbx_model_Cartn_{x,y,z}_ideal) which essentially serve as a structural template for the ligand if RDKit fails to generate conformers for that ligand.", because it seems that the user-provided coordinates are definitely used, without any attempt from SMILES (in fact the user does not provide a SMILES for custom CCDs at all).
- Regarding 4) - this is surprising, could you please clarify this? the example of a user-provided CCD (https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md) includes all hydrogens, and so do many CCDs from the PDB (e.g. 8E8 from PDB 5P9J). Do you mean that no hydrogens at all should be included in the user-provided CCD? The default value of include_hydrogens in mol_to_ccd_cif is True, and in the feautrization, mol_from_ccd_cif uses remove_hydrogens=False. On this same matter, I wonder if one should expect different results depending on the protonation state of the user-provided CCD, for example if an amine in the generated CCD is protonated or not (example: 'C=CC(=O)N1CCCC@@HC1', 'C=CC(=O)[NH+]1CCCC@@HC1').
- Regarding 5) - is there a built-in way in AF3's code to rank the output predictions from multiple seeds, giving more weight for chiral correctness, or a function to verify chiral correctness of the output predictions?

**Comment by joshabramson** [comment]
1. We do first build an rdkit Mol from the ccd cif and attempt to generate a conformer. Only if that fails do we fall back to the ideal coords. Does that address your question? Not sure I follow the suggested change to the docs.

4. We discard all hydrogens shortly after generating the Mols, so the model does not take them as input or predict them. They may be useful to generate conformers though, so probably should be included in the definitions.

5. There is not I'm afraid, and we do not have plans to add that here currently.

**Comment by YoavShamir5** [comment]
Great, thanks a lot. Regarding 1 - since the custom-ccd cif only requires the ideal coordinates as a mandatory field (and not another non-ideal coordinate set), I wrongly assumed that the initial attempt at constructing an rdkit mol is based on the SMILES. Maybe just specifying the names of the non-ideal coordinates fields (which are not mandatory) that are used during the initial generation attempt would make this clearer for others. Thanks for your input!

**Comment by yipy0005** [comment]
Hi, I would like to ask another question in relation to the CCDs: Am I understanding it correctly that for organometallic compounds, say [HB1](https://www.rcsb.org/ligand/HB1), the SMILES method would probably not work because RDKit can't process it but CCD would work because there are ideal coordinates?

Thank you for taking time to answer my query. 😁

**Comment by joshabramson** [comment]
Yes, for molecules where rdkit consistently fails to make conformers, one should use CCD instead.

**Comment by joshabramson** [comment]
> Maybe just specifying the names of the non-ideal coordinates fields (which are not mandatory) that are used during the initial generation attempt would make this clearer for others

We have updated the documentation in https://github.com/google-deepmind/alphafold3/commit/802891f85abd152ffeedbc1be80d06743c08ea26 - thanks for the suggestion

**Comment by joshabramson** [comment]
> Regarding 5) - is there a built-in way in AF3's code to rank the output predictions from multiple seeds, giving more weight for chiral correctness, or a function to verify chiral correctness of the output predictions?

We have now added this, see https://github.com/google-deepmind/alphafold3/commit/792e61e099ae011ab9d8f55768adbb95e08343b9

**Comment by joshabramson** [comment]
We simply divided the output ranking score by 100 if the output contained any chiral error. It was an arbitrary approach to create two tiers of ranking scores.

**Comment by joshabramson** [comment]
Note that the actual process of applying the chiral error checking to particular ligands and modifying the ranking score is not implemented here, but we have provided all the tools necessary to do it.
