### ISSUE TITLE
Ligand is undefined when ligands using SMILES

### ISSUE THREAD

**Issue by shenweiyan** [google-deepmind/alphafold3#215]
I tried to use SMILES as ligands input, as shown in the following json. After uploading the json file, I received a prompt **"Ligand is undefined"**. Is this a bug or is there a problem with my json file? Thank you.

[SMILE.json](https://github.com/user-attachments/files/18159447/SMILE.json)

![20241217 104953](https://github.com/user-attachments/assets/1be4f9eb-671a-4051-98bf-e9073a8b9372)

**Comment by Augustin-Zidek** [comment]
Hello, AlphaFold Server doesn't currently support defining ligands using SMILES strings, see:

https://alphafoldserver.com/faq#what-molecule-types-are-not-supported-via-alphafold-server and https://alphafoldserver.com/faq#what-biological-molecule-types-can-be-modeled-with-alphafold-server

You have to use the standalone AlphaFold 3 in order to fold ligands defined using SMILES strings.
