### ISSUE TITLE
ValueError: implementation='triton' is unsupported on this GPU generation.

### ISSUE THREAD

**Issue by yipy0005** [google-deepmind/alphafold3#46]
I was running the following:

```
#!/bin/bash

AF="af3"

singularity exec \
     --nv \
     --bind $AF/af_input:/root/af_input \
     --bind $AF/af_output:/root/af_output \
     --bind $AF/models:/root/models \
     --bind $AF/public_databases:/root/public_databases \
     alphafold3.sif \
     python alphafold3/run_alphafold.py \
     --json_path=/root/af_input/fold_input.json \
     --model_dir=/root/models \
     --db_dir=/root/public_databases \
     --output_dir=/root/af_output
```
and I got the error `ValueError: implementation='triton' is unsupported on this GPU generation.` when it was running model inference.

Appreciate if I could get some help on this. Thank you! 😁

**Comment by jacobjinkelly** [comment]
Hi @yipy0005, you can use the flag `--flash_attention_implementation=xla` (as outlined in our [performance docs](https://github.com/google-deepmind/alphafold3/blob/main/docs/performance.md#nvidia-v100-16-gb)) to disable flash attention. As @championsnet says, this will work on GPUs with compute capability <8.0. Closing the issue for now, but please feel free to re-open if you still run into any issues! :)

**Comment by jacobjinkelly** [comment]
Just wanted to flag that we improved the error message for this in [3599612](https://github.com/google-deepmind/alphafold3/commit/35996125a0f0948ff8aa24d4ac05aba1a8dbf982)

**Comment by smg3d** [comment]
> This happened for me when using an RTX 4090 with a compute capability <8.0. If you go with an A100 and compute capability >8.0, as recommended, you should be avoiding this problem.

Just to point out that the GeForce RTX 4090 **has** a compute capability > 8.0. Not that it matters, but in fact it has a higher compute capability (8.9) than the A100 (8.0).
[https://developer.nvidia.com/cuda-gpus](url)

**Comment by lauratwomey** [comment]
Hi, I'm very keen on running AF3 but running into the same error: I'm trying to run it in SLURM HPC - we have access to NVIDIA A100 and T4. Not very familiar with GPUs, so please correct me if I'm wrong, but does that mean that AF3 cannot works with either since their compute capability is <8? 
I've tried with both, also adding these flags:

export JAX_PLATFORMS=cuda
export JAX_ENABLE_TRITON=false
export CUDA_VISIBLE_DEVICES=0,1
export XLA_FLAGS="--xla_disable_hlo_passes=custom-kernel-fusion-rewriter --flash_attention_implementation=xla --xla_gpu_enable_triton_softmax_fusion=false"
export JAX_TRACEBACK_FILTERING=off

Thanks so much, and amazing work - what a fantastic tool!!
