### ISSUE TITLE
RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by Maikuraky** [google-deepmind/alphafold3#84]
```
RuntimeWarning: invalid value encountered in divide
return np.nanmean(value * mask_with_nan, axis=axis) / np.nanmean(mask_with_nan, axis=axis)
```
 in alphafold3.model.confidence.py line 337

Do we need to add an ε here to prevent the denominator from being zero?

**Comment by Augustin-Zidek** [comment]
Hi, this has already been fixed in https://github.com/google-deepmind/alphafold3/commit/0341fb7f244779a634702d7cb6e37e540e2db26a and https://github.com/google-deepmind/alphafold3/commit/08ee672e6361599dc46dd756c64b6b3c4f85a57e.

Fetching the latest code will make the warning disappear.

See also https://github.com/google-deepmind/alphafold3/issues/65.

**Comment by Augustin-Zidek** [comment]
Actually fixed in https://github.com/google-deepmind/alphafold3/commit/8073ab1ac54be5d48fd9fbf3048b6007e9e937c5 -- I missed this warning when fixing previously. Thanks for reporting.
