### ISSUE TITLE
Can I add new PDB templates 

### ISSUE THREAD

**Issue by rajanprabu** [google-deepmind/alphafold3#94]
Hi alphafold team, 

Thanks for releasing the code for academic use.  I have a small question regarding the templates that AF uses. We want to use some structures that was released last weeks and it's not yet there in the mmciif templates that AF uses ( it was dated to pdb_2022_09_28).  My question can I simply drop the new mmcif files within that folder and AF can use that ? 

Also is the database date same as 2022_09_28 the public alphfolder server ?

Thanks for your time and effort.

**Comment by Augustin-Zidek** [comment]
Hi,

you have two options:

**Option 1: Update to the newest version of PDB**

1. Put the new mmCIF files in the `mmcif_files/` directory). 
2. Update the PDB seqres FASTA file to match the version of the mmCIF files. Otherwise Hmmsearch will never find the template sequence and fetch the mmCIF file for it.
3. Update PDB seqres path using the `--seqres_database_path` flag.

**Option 2: Use custom templates**

You could manually craft the input JSON to contain the desired MSA and template(s). See https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#structural-templates for instructions. However, this is a bit fiddly, so I recommend going for option 1.

> Also is the database date same as 2022_09_28 the public alphfolder server ?

Yes, the default settings and db versions match AlphaFold Server and the AlphaFold 3 paper.

**Comment by sky1ove** [comment]
> Option 1: Update to the newest version of PDB
> 
> Put the new mmCIF files in the mmcif_files/ directory).
> Update the PDB seqres FASTA file to match the version of the mmCIF files. Otherwise Hmmsearch will never find the template sequence and fetch the mmCIF file for it.
> Update PDB seqres path using the --seqres_database_path flag.

It seems that your PDB seqres have removed some cases like 
```
>100d_A mol:na length:10  DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP*)-R(*G)-3')
CCGGCGCCGG
>100d_B mol:na length:10  DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP*)-R(*G)-3')
CCGGCGCCGG
>101d_A mol:na length:12  DNA (5'-D(*CP*GP*CP*GP*AP*AP*TP*TP*(CBR)P*GP*CP*G)-3')
CGCGAATTCGCG
```
May I ask your filter criteria? I'm asking because I want to use a similar filter criteria for the updated template database.

**Comment by kkorotkovuky** [comment]
100d is a DNA/RNA hybrid, which is not supported by the current version of AF3, I think. 101d has a modified base, CBR. I am not sure about this one; maybe it's too short?

**Comment by Augustin-Zidek** [comment]
> May I ask your filter criteria? I'm asking because I want to use a similar filter criteria for the updated template database.

Ah, yes, we have removed all non-protein (i.e. `mol:na`) sequences from it.
